"""`agentdiag init`: the files that make a directory a Workspace, and a Target in it.

D39 asks for a Manifest skeleton, a sample Suite and a gitignore entry, and — for the first
`init`, naming no Target and no Adapter — a scaffold pointing at the shipped toy Target, so
the first `agentdiag run` works before anyone has written an Adapter or found a key.

`init --target <slug>` with no `--adapter` never writes the toy (ADR-0016 §4): it writes who
the Target is, from `--name` (the slug when absent), `--description`, `--family` and
`--channel`, an Adapter of kind `pending`, and every hole under a `# REVIEW:` line.
`--adapter toy` writes the toy under any slug, `--adapter python:<module:attr>` a Target of
one's own, and the name flags apply over whichever scaffold is chosen.

Since ADR-0013 the root is a Workspace of Targets (phase-6 decision 4): `init` with no
`.agentdiag/` under the root creates one holding the Target `default` (or the one `--target`
names) at `.agentdiag/targets/<slug>/`, and `init --target <slug>` on an existing Workspace
adds that Target beside the others. A root still in the Phase 4 spelling (a Manifest directly
under `.agentdiag/`) is refused with the move that fixes it, never rearranged here: a command
that moved an author's files unasked would be the surprise this module exists to avoid.

Two rules shape everything here:

- **Nothing that already exists is overwritten.** An existing Target directory stops the
  command with exit 3 naming the path, because a Manifest is hand-edited from its first
  day and silently replacing one would lose work nothing recorded.
- **`--force` rewrites the scaffold and never the Runs.** A Run is immutable and is output,
  not source (ADR-0005 §2): re-scaffolding a Target is not permission to delete one. Nor
  the calibration notes: `judge_notes.md` (ticket 05) is written when absent and left
  alone when present, because notes are what an author learned about judging the Target,
  and a starter file is no replacement for them. The same holds for `redaction.yaml`, the
  Target's local list of names a Change record never carries (ADR-0015 §4), which `init`
  writes as an empty starter and gitignores.

After the Target's files, `init` writes the Orientation page, its two import files and the
vocabulary copy at the root through `orientation.write_orientation` (ADR-0016 §1-§3), whose
own rule is the same: a page or an import file the user wrote keeps every byte, and only the
marked Targets table is agentdiag's to regenerate. They are listed among the created paths
only when written, so a second `init --target` names `AGENTS.md` because its table changed.

The text itself lives in `templates.py`, which the checked-in examples are rendered from
(`examples/toy/`, `examples/workspace/`), so they stay the truth of what this command writes.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from pathlib import Path

from agentdiag.exits import USAGE_EXIT
from agentdiag.run.manifest_checks import review_count
from agentdiag.run.templates import (
    DEFAULT_MODEL,
    TOY_SCAFFOLD,
    Scaffold,
    UnwritableValue,
    custom_scaffold,
    pending_scaffold,
    render_judge_notes,
    render_manifest,
    render_redaction,
    render_suite,
)
from agentdiag.workspace import (
    AGENTDIAG_DIR,
    DEFAULT_SLUG,
    GITIGNORE_REDACTION_LINE,
    INDEX_FILE,
    MANIFEST_NAME,
    RESTORE_POINTS_DIRNAME,
    RUNS_DIRNAME,
    TARGETS_DIRNAME,
    NotASlug,
    TargetPaths,
    Workspace,
    WorkspaceError,
    require_slug,
)

INIT_EXIT = USAGE_EXIT
"""Usage and configuration, the same code preflight uses (D32)."""

GITIGNORE_NAME = ".gitignore"
GITIGNORE_RUNS_LINE = f"{AGENTDIAG_DIR}/{TARGETS_DIRNAME}/*/{RUNS_DIRNAME}/"
"""Every Target's Runs. Output, regenerated by `agentdiag run`, and committing them would
put a Trace of every Trial into the Workspace's history (D36, ADR-0005 §1)."""

GITIGNORE_RESTORE_POINTS_LINE = f"{AGENTDIAG_DIR}/{TARGETS_DIRNAME}/*/{RESTORE_POINTS_DIRNAME}/"
"""Every Target's Restore points (ticket 27): a copy of a deployed set, kept to undo a push,
and never source (ADR-0013 §1)."""

GITIGNORE_PLATFORM_LINE = f"{AGENTDIAG_DIR}/{TARGETS_DIRNAME}/*/platform/"
"""Every Target's in-process platform stores (ticket 27): the deployed set an in-process
Connector keeps between processes (`connector.environments.<name>.store`). It stands for a
platform's own records, so it is state, never source."""

GITIGNORE_INDEX_LINE = f"{AGENTDIAG_DIR}/{INDEX_FILE}"
"""The Workspace's derived Index (ADR-0005 §5): rebuilt from the Runs at any time, so never
source either (phase-5 decision 63)."""

GITIGNORE_LINES = (
    GITIGNORE_RUNS_LINE,
    GITIGNORE_RESTORE_POINTS_LINE,
    GITIGNORE_PLATFORM_LINE,
    GITIGNORE_INDEX_LINE,
    GITIGNORE_REDACTION_LINE,
)

LEGACY_GITIGNORE_RUNS_LINE = f"{AGENTDIAG_DIR}/{RUNS_DIRNAME}/"
"""The Runs line the Phase 4 `init` wrote. Never written now; kept where a gitignore holds
it, and the stanza it opened is where the current lines join."""

KNOWN_GITIGNORE_LINES = (LEGACY_GITIGNORE_RUNS_LINE, *GITIGNORE_LINES)

GITIGNORE_COMMENT = (
    "# Runs, Restore points, in-process platform stores and the index are output, not "
    "source: written by `agentdiag run`, a push and `agentdiag index rebuild`.\n"
    "# Each Target's redaction.yaml is local: the names it lists are never committed."
)

ADAPTER_PREFIX = "python:"
"""The Adapter form for a Target of one's own. Naming the language leaves room for the
`http:` and `cli:` Adapters later phases add, without `--adapter` changing meaning."""

TOY_ADAPTER = "toy"
"""`--adapter toy`: the shipped toy Target under any slug (ADR-0016 §4)."""


CREDENTIALS_LINE = (
    "A judged Eval needs credentials: a Claude Code login (claude auth login) "
    "or export ANTHROPIC_API_KEY=…."
)
"""The last line `init` prints for every scaffold: the two ways to supply credentials."""


class InitRefused(Exception):
    """`init` found something it will not overwrite. One message, exit 3."""


@dataclass
class InitOptions:
    """What the command was asked for, before any of it is resolved."""

    root: Path = Path(".")
    target: str | None = None
    """The slug of the Target to create; None: `default`."""

    adapter: str | None = None
    tools: str | None = None
    model: str = DEFAULT_MODEL
    force: bool = False
    name: str | None = None
    """`--name`: the Target's name; None keeps the scaffold's (the slug, for a Target whose
    Adapter is pending)."""

    description: str | None = None
    """`--description`: one sentence of what the Target does; None keeps the scaffold's."""

    family: str | None = None
    """`--family`: the persona the Target is one channel of (ADR-0013 §3)."""

    channel: str | None = None
    """`--channel`: which channel of its Family the Target is."""


@dataclass
class InitResult:
    """What `init` wrote, in the order a reader should see it named."""

    root: Path
    scaffold: Scaffold
    created: list[Path] = field(default_factory=list)
    """Absolute paths, printed relative to the root the caller named."""

    several_targets: bool = False
    """Whether the Workspace now holds more than this Target, so the next commands must
    name it with `--target`."""

    notices: list[str] = field(default_factory=list)
    """`notice: …` lines for stderr: what the Orientation page's writer left to the user."""

    reviews: int = 0
    """How many `# REVIEW:` lines the Manifest holds: what `init` asks a reader to settle
    before anything else, for a Target nothing drives yet (decision 14)."""

    @property
    def scenario_id(self) -> str:
        """The Scenario the two next commands select, so the printed lines are runnable."""
        return self.scaffold.scenario_id


def scaffold_for(options: InitOptions) -> Scaffold:
    """The scaffold this invocation writes (decision 10), with the name flags over it.

    The toy for `--adapter toy` and for the first `init`, which names neither a Target nor
    an Adapter, so the five-minute path is unchanged; the Target `--adapter python:…` names;
    and for `--target <slug>` alone, an Adapter of kind `pending`, because a slug says who a
    Target is and nothing about what drives it (ADR-0016 §4). `--name`, `--description`,
    `--family` and `--channel` then replace what the chosen scaffold says, on every scaffold.

    `--tools` is optional on purpose. A Target whose tools live behind its own factory —
    or one that has none yet — should not be made to invent a module path to satisfy the
    Manifest, so the key is omitted and the Adapter hands the factory an empty mapping.
    """
    scaffold: Scaffold
    if options.adapter == TOY_ADAPTER or (options.adapter is None and options.target is None):
        scaffold = TOY_SCAFFOLD
    elif options.adapter is None:
        assert options.target is not None
        scaffold = pending_scaffold(options.target)
    else:
        factory = parse_adapter(options.adapter)
        scaffold = custom_scaffold(
            target_name=target_name(factory, options.root),
            factory=factory,
            tools=options.tools,
            model=options.model,
        )
    return replace(
        scaffold,
        target_name=options.name if options.name is not None else scaffold.target_name,
        target_description=(
            options.description if options.description is not None else scaffold.target_description
        ),
        family=options.family if options.family is not None else scaffold.family,
        channel=options.channel if options.channel is not None else scaffold.channel,
    )


def parse_adapter(reference: str) -> str:
    """Read `python:<module:attr>` into the `module:attr` the Manifest records."""
    if not reference.startswith(ADAPTER_PREFIX):
        raise InitRefused(
            f"--adapter {reference!r} is not understood; init scaffolds two forms: "
            f"--adapter {TOY_ADAPTER} (the shipped toy Target) or "
            f"--adapter {ADAPTER_PREFIX}<module:attr> (a Target of your own)"
        )
    factory = reference[len(ADAPTER_PREFIX) :]
    if ":" not in factory or not all(part for part in factory.split(":", 1)):
        raise InitRefused(
            f"--adapter {reference!r} names no factory; "
            f"it reads {ADAPTER_PREFIX}<module>:<attribute>, "
            "as in python:my_agent.entry:make_target"
        )
    return factory


def target_name(factory: str, root: Path) -> str:
    """A readable Target name: the factory's own module, or the directory it lives in.

    The Manifest's name is what a Report and a comparison print, so it must read as the
    name of a thing rather than as an import path. The last component of the module is the
    closest agentdiag can get without asking; a factory that lives in a package's
    `__init__` names no module of its own, so the directory answers instead.
    """
    module = factory.split(":", 1)[0]
    leaf = module.rsplit(".", 1)[-1]
    if leaf in ("", "__init__") or "." not in module:
        leaf = Path(root).resolve().name
    return slug(leaf)


def slug(text: str) -> str:
    """A name a `--scenario`, a directory listing and a Report can all carry unchanged."""
    kept = [character.lower() if character.isalnum() else "-" for character in text]
    return "-".join(part for part in "".join(kept).split("-") if part) or "target"


def scaffold_target(options: InitOptions) -> InitResult:
    """Write one Target's scaffold under `options.root`, creating the Workspace when there is
    none, or refuse and say what is in the way."""
    root = Path(options.root)
    if not root.parent.exists():
        # Only the last component is created. A typo in `--root` should be a message, not
        # a tree of empty directories the caller then has to find and delete.
        raise InitRefused(
            f"{root.parent} does not exist, so {root} cannot be created; "
            "make the parent directory first, or name a --root inside one that exists"
        )
    slug = options.target if options.target is not None else DEFAULT_SLUG
    try:
        require_slug(slug)
    except NotASlug as refused:
        raise InitRefused(str(refused)) from refused

    workspace = Workspace.at(root)
    try:
        existing = workspace.targets()
    except WorkspaceError as mixed:
        raise InitRefused(str(mixed)) from mixed
    target = _target_to_write(workspace, existing, slug, options)

    scaffold = replace(scaffold_for(options), slug=slug)
    manifest = target.manifest
    suite = target.relative(scaffold.suite_path)
    notes = target.judge_notes
    redaction = target.redaction
    try:
        manifest_text, suite_text, notes_text, redaction_text = (
            render_manifest(scaffold),
            render_suite(scaffold),
            render_judge_notes(scaffold),
            render_redaction(scaffold),
        )
    except UnwritableValue as unwritable:
        # Rendered before anything is created: a value that cannot be written must not
        # leave half a scaffold behind (the preflight habit, D32).
        raise InitRefused(str(unwritable)) from unwritable

    root.mkdir(exist_ok=True)
    suite.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(manifest_text, encoding="utf-8")
    suite.write_text(suite_text, encoding="utf-8")
    created = [manifest, suite]
    for kept, text in ((notes, notes_text), (redaction, redaction_text)):
        if not kept.exists():
            kept.write_text(text, encoding="utf-8")
            created.append(kept)

    others = [other for other in existing if other.slug != slug]
    result = InitResult(
        root=root,
        scaffold=scaffold,
        created=created,
        several_targets=bool(others),
        reviews=review_count(manifest_text),
    )
    # Imported here, not at the top: orientation reaches the Registry, whose Sync breaks
    # import `agentdiag.sync.sections`, which imports `slug` from this module (a cycle).
    from agentdiag.orientation import write_orientation

    orientation = write_orientation(workspace)
    result.created += [root / name for name in orientation.written]
    result.notices += orientation.notices
    gitignore = root / GITIGNORE_NAME
    if ignore_outputs(gitignore, GITIGNORE_LINES):
        result.created.append(gitignore)
    return result


def _target_to_write(
    workspace: Workspace, existing: list[TargetPaths], slug: str, options: InitOptions
) -> TargetPaths:
    """Where this `init` writes, or `InitRefused` naming what is already there."""
    target = next((target for target in existing if target.slug == slug), None)
    if target is None:
        return workspace.new_target(slug)
    if not options.force:
        again = "agentdiag init" + ("" if options.target is None else f" --target {slug}")
        raise InitRefused(
            f"{target.directory} already exists; `{again} --force` rewrites its Manifest "
            "and sample Suite, and leaves every Run where it is"
        )
    return target


def enclosing_workspace(start: Path) -> Path | None:
    """The root of a Workspace strictly above `start`, when `start` holds none itself: what
    an `init` with no `--root` would nest a second Workspace inside (it still does, per
    phase-6 decision 4, and says so). Looked for as `Workspace.holding` does, no further up
    than the enclosing git repository's top level, so `init` and `find` agree on what is
    inside a Workspace."""
    here = Path(start).resolve()
    if (here / AGENTDIAG_DIR).is_dir():
        return None
    outer = Workspace.holding(here)
    return None if outer is None else outer.root


def ignore_outputs(path: Path, lines: tuple[str, ...] = GITIGNORE_LINES) -> bool:
    """Add the output lines to a gitignore, creating it if absent; say whether it changed.

    Idempotent per line: adding one twice would leave a developer to notice and clean up
    after a `--force`, so a line already there is left exactly as it is, and the Phase 4
    lines an older `init` wrote are kept. The lines are one stanza under one comment: a
    missing line joins the stanza an older `init` wrote, after its last line, rather than
    opening a second one.
    """
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    held = existing.splitlines()
    missing = [line for line in lines if line not in held]
    if not missing:
        return False
    known = [at for at, line in enumerate(held) if line in KNOWN_GITIGNORE_LINES]
    if known:
        at = known[-1] + 1
        held[at:at] = missing
        path.write_text("".join(f"{line}\n" for line in held), encoding="utf-8")
        return True
    prefix = existing if not existing or existing.endswith("\n") else existing + "\n"
    if prefix:
        prefix += "\n"  # a blank line, so the addition reads as its own stanza
    added = "".join(f"{line}\n" for line in missing)
    path.write_text(f"{prefix}{GITIGNORE_COMMENT}\n{added}", encoding="utf-8")
    return True


def render_created(result: InitResult) -> str:
    """What was written and what to type next — the whole of `init`'s terminal output."""
    root = Path(result.root)
    lines = [f"Wrote the scaffold into {root}:"]
    lines += [f"  {path.relative_to(root).as_posix()}" for path in result.created]
    lines += ["", *_who_and_next(result), "", CREDENTIALS_LINE]
    return "\n".join(lines)


def _who_and_next(result: InitResult) -> list[str]:
    """Who the Target is and the commands that follow, the one part that differs by
    scaffold: a Target an Adapter drives is run and shown; one whose Adapter is pending
    (decision 14) has its REVIEW lines settled, then `validate` and a dry run."""
    scaffold = result.scaffold
    naming = f" --target {scaffold.slug}" if result.several_targets else ""
    if not scaffold.pending:
        return [
            f"Target {scaffold.slug} ({scaffold.target_name}), driven by the "
            f"{scaffold.factory} factory.",
            "",
            "Next:",
            f"  agentdiag run{naming} --scenario {result.scenario_id}",
            f"  agentdiag show <run> {result.scenario_id}",
        ]
    persona = "".join(
        f", {word} {value}"
        for word, value in (("family", scaffold.family), ("channel", scaffold.channel))
        if value is not None
    )
    manifest = next(path for path in result.created if path.name == MANIFEST_NAME)
    where = manifest.relative_to(Path(result.root)).as_posix()
    return [
        f"Target {scaffold.slug} ({scaffold.target_name}){persona}; no Adapter yet "
        f"(adapter.kind: {scaffold.adapter_kind}).",
        "",
        "Next:",
        f"  settle the {result.reviews} REVIEW lines in {where}, then",
        f"  agentdiag validate{naming}",
        f"  agentdiag run{naming} --dry-run",
    ]


__all__ = [
    "ADAPTER_PREFIX",
    "GITIGNORE_INDEX_LINE",
    "GITIGNORE_LINES",
    "GITIGNORE_NAME",
    "GITIGNORE_REDACTION_LINE",
    "GITIGNORE_RESTORE_POINTS_LINE",
    "GITIGNORE_RUNS_LINE",
    "INIT_EXIT",
    "LEGACY_GITIGNORE_RUNS_LINE",
    "TOY_ADAPTER",
    "InitOptions",
    "InitRefused",
    "InitResult",
    "enclosing_workspace",
    "ignore_outputs",
    "parse_adapter",
    "render_created",
    "scaffold_for",
    "scaffold_target",
    "slug",
    "target_name",
]
