"""Seam 1: the example Suite's mechanical Evals through `agentdiag run` and `show`, in replay.

The Scenarios under the example Suite's `EXAMPLE_ONLY` marker exercise every mechanical
Eval against the toy Target. They replay from one recording whose every line is scoped to
its Scenario (phase-5 decision 19), generated by `scripts/record_fixtures.py --scripted`,
so each test here selects what it needs and the rest of the file stays invisible to it.
Each test reads what a user can observe: the summary, the exit code, `scores.json`,
`run.json`, `show`. No model is called.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

import yaml
from typer.testing import CliRunner

from agentdiag.cli import app
from agentdiag.model.prices import PRICE_TABLE_VERSION

REPO = Path(__file__).resolve().parents[1]
EXAMPLE = REPO / "examples" / "toy"
SUITE_RECORDING = REPO / "tests" / "fixtures" / "recordings" / "toy-orders.jsonl"

CANCEL = "cancel-processing-order"
WHERE = "where-is-shipped-order"
LOOKUP_THEN_CANCEL = "lookup-then-cancel"
STATUS = "status-question-is-not-a-cancel"
UNSEEN = "lookup-with-unseen-arguments"
GREETING = "greeting-calls-no-tool"
JUDGED = [
    "delivered-order-cannot-be-cancelled",
    "order-details-come-from-the-lookup",
    "status-lookup-asks-for-the-named-order",
    "cancel-looks-up-then-cancels",
    "authored-lists-decide-without-a-judge",
    "cancel-with-a-promised-refund-date",
]
"""The Scenarios ticket 05 added for the judged Evals; the last is the guardrails Suite's."""

ADAPTIVE = "cancel-without-the-order-number"
"""The example's adaptive Scenario (ticket 06): a scripted opener and a simulated tail."""

EVERY_SCENARIO = [CANCEL, WHERE, LOOKUP_THEN_CANCEL, STATUS, UNSEEN, GREETING, *JUDGED, ADAPTIVE]

runner = CliRunner()


def target_root(tmp_path: Path) -> Path:
    root = tmp_path / "toy"
    shutil.copytree(EXAMPLE, root, ignore=shutil.ignore_patterns("runs"))
    return root


def run(root: Path, *scenarios: str, extra: tuple[str, ...] = ()) -> Any:
    selection = [argument for scenario in scenarios for argument in ("--scenario", scenario)]
    return runner.invoke(
        app,
        ["run", "--root", str(root), *selection, *extra, "--replay", str(SUITE_RECORDING)],
    )


def only_run(root: Path) -> Path:
    (run_dir,) = (root / ".agentdiag" / "targets" / "toy-order-desk" / "runs").iterdir()
    return run_dir


def scores(root: Path, scenario: str) -> list[dict[str, Any]]:
    path = only_run(root) / "trials" / scenario / "1" / "scores.json"
    return list(json.loads(path.read_text(encoding="utf-8"))["scores"])


def verdicts(root: Path, scenario: str) -> dict[str, tuple[str, str | None]]:
    return {score["eval"]: (score["verdict"], score["reason"]) for score in scores(root, scenario)}


def edit_manifest(root: Path, **fields: Any) -> None:
    path = root / ".agentdiag" / "targets" / "toy-order-desk" / "manifest.yaml"
    manifest = yaml.safe_load(path.read_text(encoding="utf-8"))
    manifest.update(fields)
    path.write_text(yaml.safe_dump(manifest), encoding="utf-8")


def show(root: Path, scenario: str) -> str:
    result = runner.invoke(app, ["show", only_run(root).name, scenario, "--root", str(root)])
    assert result.exit_code == 0, result.output
    return str(result.stdout)


# --- one Scenario per Verdict the example Suite exists to show ---


def test_a_scenario_whose_every_mechanical_eval_passes_exits_0(tmp_path: Path) -> None:
    root = target_root(tmp_path)

    result = run(root, WHERE)

    assert result.exit_code == 0, result.stdout
    assert set(verdicts(root, WHERE).values()) == {("pass", None)}
    assert len(verdicts(root, WHERE)) == 10


def test_a_target_that_cancels_an_order_it_was_only_asked_about_fails_and_exits_1(
    tmp_path: Path,
) -> None:
    root = target_root(tmp_path)

    result = run(root, STATUS)

    assert result.exit_code == 1, result.stdout
    assert verdicts(root, STATUS) == {
        "expect_tools": ("pass", None),
        "forbid_tools": ("fail", None),
        "must_not_say": ("fail", None),
    }
    assert "  forbid_tools  fail" in result.stdout
    assert "  must_not_say  fail" in result.stdout


def test_arguments_the_adapter_could_not_see_are_unverifiable_and_exit_2(tmp_path: Path) -> None:
    root = target_root(tmp_path)

    result = run(root, UNSEEN)

    assert result.exit_code == 2, result.stdout
    assert verdicts(root, UNSEEN) == {
        "expect_tools": ("pass", None),
        "expect_tool_args": ("unverifiable", "evidence_missing"),
        "first_token_latency": ("unverifiable", "evidence_missing"),
    }
    assert "  expect_tool_args  unverifiable  evidence_missing" in result.stdout


def test_a_greeting_that_called_no_tool_passes_its_tool_evals_on_the_instrumented_fact(
    tmp_path: Path,
) -> None:
    """Decision 3: in an instrumented Trace, no tool Span means no tool was called."""
    root = target_root(tmp_path)

    result = run(root, GREETING)

    assert result.exit_code == 0, result.stdout
    by_eval = {score["eval"]: score for score in scores(root, GREETING)}
    assert by_eval["forbid_tools"]["verdict"] == "pass"
    assert by_eval["forbid_tools"]["evidence"] == ["llm_call-1"]
    assert by_eval["tool_count_max"]["verdict"] == "pass"


def test_turn_restricted_evals_read_only_their_own_turn(tmp_path: Path) -> None:
    root = target_root(tmp_path)

    result = run(root, LOOKUP_THEN_CANCEL)

    assert result.exit_code == 0, result.stdout
    by_eval = {
        (score["eval"], score["verdict"]): score["evidence"]
        for score in scores(root, LOOKUP_THEN_CANCEL)
    }
    assert by_eval[("forbid_tools", "pass")] == ["retrieval-1"]
    assert by_eval[("expect_tools", "pass")] == ["tool_call-1"]
    assert by_eval[("must_say_any", "pass")] == ["turn-2"]


def test_the_whole_example_suite_replays_from_one_scoped_recording(tmp_path: Path) -> None:
    """Decision 19: every Scenario's Trial walks its own view of one file."""
    root = target_root(tmp_path)

    result = run(root, *EVERY_SCENARIO)

    assert result.exit_code == 1, result.stdout
    last = next(line for line in result.stdout.splitlines() if "pass rate" in line)
    # Ticket 04's 24 mechanical Scores, the cancel Scenario's prompt_adherence — the
    # Judge's fail on rule 3 (`tests/stories.py`) — ticket 05's ten: goal,
    # data_grounding, data_query, tool_choice, the three of the authored-lists Scenario,
    # and one per guardrail rule, of which no-refund-timing fails — and ticket 06's two
    # passes over the adaptive Scenario, `expect_tools_order` and its `goal`.
    assert last.startswith(
        "pass 33  fail 4  incomplete 0  unverifiable 2  invalid 0  pass rate 89% (33 of 37)"
    )
    assert "not run 0" in last
    for scenario in EVERY_SCENARIO:
        assert f"{scenario}  trial 1" in result.stdout
        terminations = [
            json.loads(line)["termination"]
            for line in (only_run(root) / "trials" / scenario / "1" / "trace.jsonl")
            .read_text(encoding="utf-8")
            .splitlines()
            if json.loads(line)["type"] == "trace/end"
        ]
        # A Scenario of literal Turns completes; the adaptive one ends on its criterion.
        assert terminations == ["stop_when" if scenario == ADAPTIVE else "completed"]


def test_every_mechanical_score_stores_its_evidence_fidelity_and_code(tmp_path: Path) -> None:
    root = target_root(tmp_path)

    run(root, WHERE)

    for score in scores(root, WHERE):
        assert score["evidence"], score
        assert score["fidelity"] == "instrumented"
        assert score["source"]["kind"] == "mechanical"
        assert score["source"]["code"].startswith("agentdiag.eval.")


def test_a_latency_score_stores_its_value_threshold_and_direction(tmp_path: Path) -> None:
    """ADR-0003 §5: a later threshold change never re-interprets a stored Score."""
    root = target_root(tmp_path)

    run(root, WHERE)

    by_eval = {score["eval"]: score for score in scores(root, WHERE)}
    tool = by_eval["tool_latency"]
    response = by_eval["response_latency"]
    assert tool["threshold"] == {"max_ms": 1000}
    assert response["threshold"] == {"max_ms": 30000}
    assert tool["direction"] == response["direction"] == "minimize"
    assert isinstance(tool["value"], float) and tool["value"] <= 1000
    assert isinstance(response["value"], float) and response["value"] <= 30000


def test_every_mechanical_eval_needs_no_credentials_and_writes_no_judgement(
    tmp_path: Path,
) -> None:
    root = target_root(tmp_path)

    run(root, WHERE)

    assert json.loads((only_run(root) / "run.json").read_text(encoding="utf-8"))["judge"] is None
    assert not (only_run(root) / "trials" / WHERE / "1" / "judgement.jsonl").exists()


# --- forbidden_phrases from the Manifest: empty is distinct from omitted (decision 6) ---


def test_a_manifest_without_forbidden_phrases_adds_no_score(tmp_path: Path) -> None:
    root = target_root(tmp_path)

    run(root, STATUS)

    assert "forbidden_phrases" not in verdicts(root, STATUS)


def test_an_empty_manifest_list_gives_every_scenario_a_passing_inherited_score(
    tmp_path: Path,
) -> None:
    root = target_root(tmp_path)
    edit_manifest(root, forbidden_phrases=[])

    run(root, STATUS, GREETING)

    for scenario in (STATUS, GREETING):
        (inherited,) = [s for s in scores(root, scenario) if s["eval"] == "forbidden_phrases"]
        assert inherited["verdict"] == "pass"
        assert "The Manifest declares no forbidden phrases" in inherited["rationale"]
    summary = json.loads((only_run(root) / "run.json").read_text(encoding="utf-8"))["scenarios"]
    for entry in summary:
        assert {
            "eval": "forbidden_phrases",
            "id": None,
            "inherited": True,
            "params": {},
            "threshold": None,
        } in entry["evals"]


def test_the_manifests_forbidden_phrases_are_screened_in_every_scenario(tmp_path: Path) -> None:
    root = target_root(tmp_path)
    edit_manifest(root, forbidden_phrases=["cancelled"])

    result = run(root, STATUS, GREETING)

    assert result.exit_code == 1
    assert verdicts(root, STATUS)["forbidden_phrases"] == ("fail", None)
    assert verdicts(root, GREETING)["forbidden_phrases"] == ("pass", None)


def test_a_scenario_that_declares_forbidden_phrases_adds_to_the_manifests_in_one_score(
    tmp_path: Path,
) -> None:
    root = target_root(tmp_path)
    edit_manifest(root, forbidden_phrases=["refund"])

    run(root, WHERE)

    (screened,) = [s for s in scores(root, WHERE) if s["eval"] == "forbidden_phrases"]
    assert screened["verdict"] == "pass"
    assert "the Manifest's 1 and the Scenario's 2" in screened["rationale"]


# --- the Manifest's tools section and the retrieval kind (D37, ADR-0006 §2) ---


def test_the_lookup_the_manifest_marks_retrieval_is_a_retrieval_span_in_the_trace(
    tmp_path: Path,
) -> None:
    root = target_root(tmp_path)

    run(root, LOOKUP_THEN_CANCEL)

    kinds = [
        (event["span_id"], event["kind"])
        for event in (
            json.loads(line)
            for line in (only_run(root) / "trials" / LOOKUP_THEN_CANCEL / "1" / "trace.jsonl")
            .read_text(encoding="utf-8")
            .splitlines()
        )
        if event["type"] == "span/start" and event["kind"] in {"retrieval", "tool_call"}
    ]
    assert kinds == [("retrieval-1", "retrieval"), ("tool_call-1", "tool_call")]


def test_show_prints_each_tool_span_under_its_kind(tmp_path: Path) -> None:
    root = target_root(tmp_path)
    run(root, LOOKUP_THEN_CANCEL)

    shown = show(root, LOOKUP_THEN_CANCEL)

    assert "retrieval-1  execute_tool lookup_order" in shown
    assert "tool_call-1  execute_tool cancel_order" in shown


def test_a_tool_kind_outside_retrieval_and_action_is_a_preflight_error(tmp_path: Path) -> None:
    root = target_root(tmp_path)
    edit_manifest(root, tools={"lookup_order": {"kind": "lookup"}})

    result = run(root, WHERE)

    assert result.exit_code == 3, result.stdout
    assert "retrieval" in result.stdout
    assert not (root / ".agentdiag" / "targets" / "toy-order-desk" / "runs").exists()


def test_the_run_record_carries_the_manifests_tools_section(tmp_path: Path) -> None:
    root = target_root(tmp_path)

    run(root, WHERE)

    record = json.loads((only_run(root) / "run.json").read_text(encoding="utf-8"))
    assert record["manifest"]["tools"] == {
        "lookup_order": {"kind": "retrieval", "schema": None, "side_effects": "none"},
        "cancel_order": {"kind": "action", "schema": None, "side_effects": "none"},
    }
    assert record["manifest"]["forbidden_phrases"] is None


# --- cost, per model Span, per actor, and the price table's version (decisions 4, 5) ---


def test_the_run_record_names_the_price_table_its_spans_were_costed_under(tmp_path: Path) -> None:
    root = target_root(tmp_path)

    run(root, WHERE)

    record = json.loads((only_run(root) / "run.json").read_text(encoding="utf-8"))
    assert record["price_table"] == {"version": PRICE_TABLE_VERSION}


def test_show_prints_the_cost_of_every_model_span_and_of_each_actor(tmp_path: Path) -> None:
    """claude-sonnet-5: 738 in, 57 out is $0.002046; 871 in, 26 out is $0.002002."""
    root = target_root(tmp_path)
    run(root, WHERE)

    shown = show(root, WHERE)

    assert "$0.002046" in next(line for line in shown.splitlines() if "llm_call-1" in line)
    assert "$0.002002" in next(line for line in shown.splitlines() if "llm_call-2" in line)
    assert "Cost target $0.004048" in shown


def test_show_prints_the_judges_cost_beside_the_targets(tmp_path: Path) -> None:
    root = target_root(tmp_path)
    run(root, CANCEL)

    shown = show(root, CANCEL)

    # Two Judge calls, the Eval's and the Diagnosis's (D24), each priced on its Span. The
    # cancel Trial's Judge answers are captured (ticket 21, decision 41), so their cost is
    # read from the Spans rather than written here; the Target's is authored.
    judgement = only_run(root) / "trials" / CANCEL / "1" / "judgement.jsonl"
    costs = [
        event["attributes"]["llm.cost.total"]
        for event in map(json.loads, judgement.read_text(encoding="utf-8").splitlines())
        if event["type"] == "span/end"
    ]
    assert len(costs) == 2
    assert f"Cost target $0.006900 · judge ${round(sum(costs), 6):.6f}" in shown
    assert f"${costs[0]:.6f}" in next(line for line in shown.splitlines() if "judge-1" in line)


def test_metrics_are_on_every_span_whether_or_not_an_eval_thresholds_them(tmp_path: Path) -> None:
    """ADR-0003 §6: `lookup-then-cancel` declares no latency Eval; its Spans still say how long."""
    root = target_root(tmp_path)
    run(root, LOOKUP_THEN_CANCEL)

    shown = show(root, LOOKUP_THEN_CANCEL)

    for span_id in ("llm_call-1", "retrieval-1", "llm_call-3", "tool_call-1"):
        line = next(line for line in shown.splitlines() if line.strip().startswith(span_id))
        assert " ms" in line
    assert shown.count("$0.00") >= 4


def test_show_prints_unpriced_for_a_model_the_price_table_does_not_price(tmp_path: Path) -> None:
    """A Trace an Adapter wrote for an unpriced model: no cost attribute, so `unpriced`."""
    root = target_root(tmp_path)
    run(root, GREETING)
    trace = only_run(root) / "trials" / GREETING / "1" / "trace.jsonl"
    lines = []
    for line in trace.read_text(encoding="utf-8").splitlines():
        event = json.loads(line)
        if event["type"] == "span/end" and event["span_id"] == "llm_call-1":
            for name in [key for key in event["attributes"] if key.startswith("llm.cost.")]:
                event["attributes"].pop(name)
            event["attributes"]["gen_ai.response.model"] = "claude-mystery-1"
        lines.append(json.dumps(event, ensure_ascii=False))
    trace.write_text("\n".join(lines) + "\n", encoding="utf-8")

    shown = show(root, GREETING)

    assert "unpriced" in next(line for line in shown.splitlines() if "llm_call-1" in line)
    assert "Cost target unpriced" in shown
    assert "$0.000000" not in shown


def test_a_run_recorded_before_cost_was_stamped_still_reads(tmp_path: Path) -> None:
    """A Phase 4 `run.json` has no `price_table`; it reads as None and `show` still renders."""
    from agentdiag.run.record import RunRecord

    root = target_root(tmp_path)
    run(root, GREETING)
    path = only_run(root) / "run.json"
    record = json.loads(path.read_text(encoding="utf-8"))
    del record["price_table"]
    path.write_text(json.dumps(record), encoding="utf-8")

    assert RunRecord.model_validate(record).price_table is None
    assert "Scores" in show(root, GREETING)
