"""Seam 1: `agentdiag compare` over the committed Run fixtures (D33, ADR-0005 §6, ticket 08).

Every Run compared here is a directory under `tests/fixtures/runs/`, written by
`scripts/record_fixtures.py --runs` and regenerated byte for byte by
`tests/test_run_fixtures.py`. What each one is:

- `base`: the Baseline, four Scenarios of the example, judged by `claude-opus-5`.
- `swap`: the Target's model swapped to `claude-sonnet-4-6`; its reply about a shipped order
  now says "refund", which `must_not_say` forbids.
- `prmt`: the same reply, with the model unchanged and `manifest.prompts` gaining a second
  pointer, a local-only revision of the rules: the change a caller declares.
- `part`: the Baseline's Scenarios without `greeting-calls-no-tool`.
- `jdge`: the Baseline's Target, judged by `claude-opus-5-5`, which fails the `goal` the
  default Judge passed.
- `resc`: a rescore of the Baseline under the same Judge.
- `thrs`: a second rescore of the Baseline, after `response_latency` on the shipped order was
  tightened to `max_ms: 1` in the Suite.

"regression" is a label, and the word appears in the output only on an actual one.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from typer.testing import CliRunner

from agentdiag.cli import app
from agentdiag.run.compare import CitesRead, Comparison, ScoreDelta

REPO = Path(__file__).resolve().parents[1]
RUNS = REPO / "tests" / "fixtures" / "runs"
BASELINE = RUNS / "20260923T100000Z-base"
MODEL_SWAP = RUNS / "20260923T100100Z-swap"
PROMPT_CHANGE = RUNS / "20260923T100200Z-prmt"
PARTIAL = RUNS / "20260923T100300Z-part"
JUDGE_SWAP = RUNS / "20260923T100400Z-jdge"
RESCORE = RUNS / "20260923T100500Z-resc"
THRESHOLD = RUNS / "20260923T100700Z-thrs"

SHIPPED = "where-is-shipped-order"
GREETING = "greeting-calls-no-tool"
JUDGED = "delivered-order-cannot-be-cancelled"

runner = CliRunner()


def compare(*arguments: str | Path) -> tuple[int, str]:
    result = runner.invoke(app, ["compare", *(str(argument) for argument in arguments)])
    return result.exit_code, result.stdout + result.stderr


def comparison(*arguments: str | Path) -> Comparison:
    result = runner.invoke(app, ["compare", *(str(a) for a in arguments), "--json"])
    assert result.exit_code == 0, result.stdout + result.stderr
    return Comparison.model_validate_json(result.stdout)


def delta(found: Comparison, scenario: str, eval: str) -> ScoreDelta:
    return next(d for d in found.deltas if d.scenario == scenario and d.eval == eval)


# --- a Target model swap is an undeclared difference, and no regression is claimed ---


def test_a_target_model_swap_is_listed_as_an_undeclared_difference_once() -> None:
    """The Manifest's environment block is diffed; `adapter.config`, its verbatim copy, is not."""
    code, text = compare(BASELINE, MODEL_SWAP)

    assert code == 0
    assert [d.path for d in comparison(BASELINE, MODEL_SWAP).differences] == [
        "manifest.adapter.environments.local.model"
    ]
    assert (
        "  undeclared  manifest.adapter.environments.local.model  claude-sonnet-5 -> "
        "claude-sonnet-4-6"
    ) in text.splitlines()


def test_across_an_undeclared_model_swap_the_moved_score_is_labelled_changed() -> None:
    found = comparison(BASELINE, MODEL_SWAP)

    moved = delta(found, SHIPPED, "must_not_say")
    assert (moved.baseline.mean, moved.run.mean) == (1.0, 0.0)
    assert moved.label == "changed"
    assert moved.because == ["manifest.adapter.environments.local.model"]
    assert found.summary.endswith("1 undeclared difference: moved deltas are labelled changed")


def test_declaring_the_documented_model_path_alone_reports_the_regression() -> None:
    found = comparison(
        BASELINE, MODEL_SWAP, "--expect", "manifest.adapter.environments.local.model"
    )

    assert delta(found, SHIPPED, "must_not_say").label == "regression"
    assert found.counts == {"regression": 1, "unchanged": 16}


def test_the_word_regression_appears_only_as_the_label_of_an_actual_one() -> None:
    """Across an undeclared difference nothing is a regression, so the word is absent from
    the text and the JSON alike: no zero count, no "no regression claimed"."""
    _, text = compare(BASELINE, MODEL_SWAP)
    result = runner.invoke(app, ["compare", str(BASELINE), str(MODEL_SWAP), "--json"])
    _, judged_text = compare(BASELINE, JUDGE_SWAP, "--expect", "judge.model")

    assert "regression" not in text
    assert "regression" not in result.stdout
    assert "regression" not in judged_text


def test_every_delta_prints_the_because_its_json_carries() -> None:
    """D33: the text and `--json` are the same content, `unchanged` deltas included."""
    _, text = compare(BASELINE, MODEL_SWAP)

    assert (
        "  expect_tools  mean 1.00 -> 1.00  delta +0.00  unchanged"
        "  because manifest.adapter.environments.local.model  abnormal none -> none"
    ) in text.splitlines()


def test_the_configuration_diff_comes_before_any_score() -> None:
    _, text = compare(BASELINE, MODEL_SWAP)
    lines = text.splitlines()

    configuration = lines.index("configuration  1 difference(s)")
    scenarios = lines.index("scenarios  4 in both")
    first_score = next(i for i, line in enumerate(lines) if line.startswith("  expect_tools "))
    assert configuration < scenarios < first_score
    assert lines[-1].startswith("unchanged 16  changed 1  1 undeclared difference")


# --- an edited threshold moves a Verdict without the Target changing ---
#
# `resc` and `thrs` are two rescores of the Baseline's Traces; before the second, the
# Suite's where-is-shipped-order declared `response_latency: {max_ms: 1}` instead of 30000.


def test_a_verdict_a_threshold_edit_flipped_is_a_delta_in_the_pass_rate() -> None:
    found = comparison(RESCORE, THRESHOLD)

    moved = delta(found, SHIPPED, "response_latency")
    assert (moved.baseline.mean, moved.run.mean, moved.delta) == (1.0, 0.0, -1.0)
    assert (moved.baseline.value_mean, moved.run.value_mean, moved.value_delta) == (
        16.0,
        16.0,
        0.0,
    )
    assert moved.run.direction == "minimize"


def test_the_threshold_edit_is_an_undeclared_difference_and_withholds_regression() -> None:
    found = comparison(RESCORE, THRESHOLD)

    assert [(d.path, d.baseline, d.run, d.declared) for d in found.differences] == [
        (f"scenarios.{SHIPPED}.evals.response_latency.threshold.max_ms", 30000, 1, False)
    ]
    assert delta(found, SHIPPED, "response_latency").label == "changed"
    assert "regression" not in found.counts


def test_declaring_the_eval_declaration_reports_the_regression() -> None:
    found = comparison(
        RESCORE, THRESHOLD, "--expect", f"scenarios.{SHIPPED}.evals.response_latency"
    )

    assert delta(found, SHIPPED, "response_latency").label == "regression"
    assert found.summary == (
        "regression 1  unchanged 16  declared differences only: "
        f"scenarios.{SHIPPED}.evals.response_latency.threshold.max_ms"
    )
    assert comparison(RESCORE, THRESHOLD, "--expect", "scenarios").counts["regression"] == 1


def test_a_metric_delta_shows_its_value_and_direction_beside_the_pass_rate() -> None:
    _, text = compare(RESCORE, THRESHOLD)

    line = next(line for line in text.splitlines() if line.startswith("  response_latency "))
    assert line.startswith(
        "  response_latency  mean 1.00 -> 0.00  delta -1.00"
        "  value (minimize) 16.00 -> 16.00  value delta +0.00  changed"
    )


def test_a_malformed_run_record_is_a_usage_error_not_a_silent_comparison(tmp_path: Path) -> None:
    broken = tmp_path / "broken"
    shutil.copytree(MODEL_SWAP, broken)
    record = json.loads((broken / "run.json").read_text(encoding="utf-8"))
    del record["adapter"]
    (broken / "run.json").write_text(json.dumps(record), encoding="utf-8")

    code, text = compare(BASELINE, broken)

    assert code == 3
    assert "is not a Run" in text


# --- a declared prompt change reports regressions ---


def test_a_declared_prompt_change_reports_the_regression_it_caused() -> None:
    found = comparison(BASELINE, PROMPT_CHANGE, "--expect", "manifest.prompts")

    assert [(d.path, d.declared) for d in found.differences] == [
        ("manifest.prompts.rules.local_only", True),
        ("manifest.prompts.rules.path", True),
    ]
    assert delta(found, SHIPPED, "must_not_say").label == "regression"
    assert found.counts["regression"] == 1
    assert found.summary.endswith(
        "declared differences only: manifest.prompts.rules.local_only, manifest.prompts.rules.path"
    )


def test_the_same_prompt_change_left_undeclared_claims_no_regression() -> None:
    found = comparison(BASELINE, PROMPT_CHANGE)

    assert delta(found, SHIPPED, "must_not_say").label == "changed"
    assert "regression" not in found.counts


def test_an_expect_prefix_covers_every_path_under_it_by_whole_segments() -> None:
    assert comparison(BASELINE, PROMPT_CHANGE, "--expect", "manifest").counts["regression"] == 1

    code, text = compare(BASELINE, PROMPT_CHANGE, "--expect", "manifest.prom")
    assert code == 3
    assert "--expect names nothing in either Run: manifest.prom" in text


def test_a_regression_line_says_regression_and_its_abnormal_counts_beside_it() -> None:
    _, text = compare(BASELINE, PROMPT_CHANGE, "--expect", "manifest.prompts")

    assert (
        "  must_not_say  mean 1.00 -> 0.00  delta -1.00  regression  abnormal none -> none"
    ) in text.splitlines()


# --- a partial Run against a full one ---


def test_a_partial_run_names_the_scenarios_it_lacks_and_compares_only_the_intersection() -> None:
    found = comparison(BASELINE, PARTIAL)

    assert found.scenarios.only_in_baseline == [GREETING]
    assert found.scenarios.only_in_run == []
    assert GREETING not in {d.scenario for d in found.deltas}
    assert {d.scenario for d in found.deltas} == set(found.scenarios.intersection)
    _, text = compare(BASELINE, PARTIAL)
    assert f"  only in baseline 1: {GREETING}" in text.splitlines()


def test_the_scenarios_only_one_run_holds_are_named_on_either_side() -> None:
    found = comparison(PARTIAL, BASELINE)

    assert found.scenarios.only_in_run == [GREETING]
    assert found.scenarios.only_in_baseline == []


# --- two Runs judged by different models ---


def test_a_judge_model_change_states_before_any_score_that_the_comparison_is_invalid() -> None:
    _, text = compare(BASELINE, JUDGE_SWAP)
    lines = text.splitlines()

    statement = next(i for i, line in enumerate(lines) if line.startswith("judge  "))
    assert "the Score comparison is invalid across a Judge change" in lines[statement]
    first_score = next(i for i, line in enumerate(lines) if line.startswith("  expect_tools "))
    assert statement < first_score


def test_every_judged_delta_across_a_judge_change_is_marked_and_no_mechanical_one_is() -> None:
    found = comparison(BASELINE, JUDGE_SWAP)

    judged = delta(found, JUDGED, "goal")
    assert (judged.baseline.mean, judged.run.mean) == (1.0, 0.0)
    assert judged.judge_changed is True
    assert judged.label == "changed"
    assert judged.because == ["judge.model"]
    assert not any(d.judge_changed for d in found.deltas if d.scenario != JUDGED)


def test_declaring_the_judge_model_says_the_deltas_measure_the_judge_and_still_withholds_it() -> (
    None
):
    found = comparison(BASELINE, JUDGE_SWAP, "--expect", "judge.model")

    assert found.judge_statements == [
        "the judged deltas measure the Judge, not the Target (judge.model declared); "
        "judged deltas are labelled judge changed"
    ]
    assert delta(found, JUDGED, "goal").label == "changed"
    assert "regression" not in found.counts
    assert found.summary.endswith("declared differences only: judge.model")


# --- two Runs judged through different Backends (ticket 19, decision 26) ---

CLAUDE_CODE = {"kind": "claude_code", "cli_version": "2.1.280"}
BACKEND_STATEMENT = (
    "the Judge Backend changed (judge.backend.cli_version, judge.backend.kind; structured "
    "output as recorded -> checked after the fact, one retry): the Score comparison is "
    "invalid across it; judged deltas are labelled judge changed"
)
"""Replay to Claude Code: the kinds differ, so the statement names both modes (decision 44)."""


def judged_through(run: Path, tmp_path: Path, backend: dict[str, str | None]) -> Path:
    """A copy of a fixture Run whose `run.json` says its Judge took another Backend."""
    copy = tmp_path / run.name
    shutil.copytree(run, copy)
    record = json.loads((copy / "run.json").read_text(encoding="utf-8"))
    record["judge"]["backend"] = backend
    (copy / "run.json").write_text(json.dumps(record, indent=2), encoding="utf-8")
    return copy


def test_a_judge_backend_change_is_its_own_statement_before_any_score(tmp_path: Path) -> None:
    through_claude_code = judged_through(BASELINE, tmp_path, CLAUDE_CODE)

    found = comparison(BASELINE, through_claude_code)
    _, text = compare(BASELINE, through_claude_code)

    assert [(d.path, d.baseline, d.run, d.declared) for d in found.differences] == [
        ("judge.backend.cli_version", None, "2.1.280", False),
        ("judge.backend.kind", "replay", "claude_code", False),
    ]
    assert found.judge_statements == [BACKEND_STATEMENT]
    lines = text.splitlines()
    assert lines.index(f"judge  {BACKEND_STATEMENT}") < next(
        i for i, line in enumerate(lines) if line.startswith("  expect_tools ")
    )


def test_every_judged_delta_across_a_backend_change_is_marked_and_no_mechanical_one_is(
    tmp_path: Path,
) -> None:
    found = comparison(BASELINE, judged_through(BASELINE, tmp_path, CLAUDE_CODE))

    judged = [d for d in found.deltas if (d.baseline and d.baseline.judged)]
    assert judged
    assert all(d.judge_changed for d in judged)
    assert not any(d.judge_changed for d in found.deltas if d not in judged)
    assert "regression" not in found.counts


def test_a_backend_change_beside_a_judge_model_change_labels_the_moved_delta_changed(
    tmp_path: Path,
) -> None:
    found = comparison(BASELINE, judged_through(JUDGE_SWAP, tmp_path, CLAUDE_CODE))

    goal = delta(found, JUDGED, "goal")
    assert goal.label == "changed"
    assert goal.because == ["judge.backend.cli_version", "judge.backend.kind", "judge.model"]
    assert found.judge_statements[1] == BACKEND_STATEMENT


def test_a_declared_backend_change_is_said_to_be_declared_and_still_claims_no_regression(
    tmp_path: Path,
) -> None:
    found = comparison(
        BASELINE, judged_through(JUDGE_SWAP, tmp_path, CLAUDE_CODE), "--expect", "judge"
    )

    assert found.judge_statements[1] == (
        "the Judge Backend changed (judge.backend.cli_version, judge.backend.kind declared; "
        "structured output as recorded -> checked after the fact, one retry): the judged "
        "deltas measure the Judge, not the Target; judged deltas are labelled judge changed"
    )
    assert delta(found, JUDGED, "goal").label == "changed"
    assert "regression" not in found.counts


def test_a_backend_change_from_the_api_to_claude_code_names_both_structured_output_modes(
    tmp_path: Path,
) -> None:
    """Decision 44: a schema `pattern` is a guarantee on one side and an instruction plus a
    check on the other, and the statement says which is which."""
    (tmp_path / "api").mkdir()
    (tmp_path / "cli").mkdir()
    api = judged_through(BASELINE, tmp_path / "api", {"kind": "anthropic_api", "cli_version": None})
    cli = judged_through(BASELINE, tmp_path / "cli", CLAUDE_CODE)

    found = comparison(api, cli)

    assert found.judge_statements == [
        "the Judge Backend changed (judge.backend.cli_version, judge.backend.kind; structured "
        "output constrained at decoding -> checked after the fact, one retry): the Score "
        "comparison is invalid across it; judged deltas are labelled judge changed"
    ]


def test_a_cli_version_change_alone_names_no_structured_output_modes(tmp_path: Path) -> None:
    (tmp_path / "old").mkdir()
    (tmp_path / "new").mkdir()
    older = judged_through(BASELINE, tmp_path / "old", CLAUDE_CODE)
    newer = judged_through(
        BASELINE, tmp_path / "new", {"kind": "claude_code", "cli_version": "2.1.281"}
    )

    found = comparison(older, newer)

    assert found.judge_statements == [
        "the Judge Backend changed (judge.backend.cli_version): the Score comparison is "
        "invalid across it; judged deltas are labelled judge changed"
    ]


def test_a_run_that_records_no_backend_says_whether_the_path_changed_is_unknown(
    tmp_path: Path,
) -> None:
    """A Run written before ticket 19 has no `judge.backend`: nothing is claimed either way."""
    older = tmp_path / "older"
    shutil.copytree(BASELINE, older)
    record = json.loads((older / "run.json").read_text(encoding="utf-8"))
    del record["judge"]["backend"]
    (older / "run.json").write_text(json.dumps(record, indent=2), encoding="utf-8")

    found = comparison(older, BASELINE)

    assert [(d.path, d.baseline, d.run) for d in found.differences] == [
        ("judge.backend.kind", None, "replay")
    ]
    assert found.judge_statements == [
        "one Run records no Judge Backend (judge.backend.kind): whether the path changed is "
        "unknown; judged deltas are labelled judge changed"
    ]
    assert all(d.judge_changed for d in found.deltas if d.baseline and d.baseline.judged)


# --- a rescore compared to its source ---


def test_a_rescore_and_its_source_are_flagged_as_sharing_traces() -> None:
    code, text = compare(BASELINE, RESCORE)

    assert code == 0
    assert "the two Runs share Traces: only the judgement differs" in text.splitlines()
    assert comparison(RESCORE, BASELINE).shared_traces is True


def test_a_rescore_under_the_same_configuration_has_identical_mechanical_deltas() -> None:
    found = comparison(BASELINE, RESCORE)

    mechanical = [d for d in found.deltas if not (d.baseline and d.baseline.judged)]
    assert mechanical
    assert all(d.delta == 0 and d.label == "unchanged" for d in mechanical)
    assert all(d.baseline == d.run for d in mechanical)
    assert found.differences == []
    assert found.summary == "unchanged 17  no configuration difference"


def test_two_runs_that_share_no_traces_are_not_flagged() -> None:
    assert comparison(BASELINE, MODEL_SWAP).shared_traces is False


# --- the JSON, the exit codes, and what compare reads ---


def test_compare_json_round_trips_through_the_comparison_model() -> None:
    result = runner.invoke(
        app, ["compare", str(BASELINE), str(JUDGE_SWAP), "--expect", "judge.model", "--json"]
    )

    parsed = Comparison.model_validate_json(result.stdout)
    assert json.loads(parsed.model_dump_json()) == json.loads(result.stdout)
    assert parsed.judge_statements and parsed.deltas and parsed.differences


def test_a_run_that_does_not_exist_is_a_usage_error(tmp_path: Path) -> None:
    (tmp_path / ".agentdiag").mkdir()
    code, text = compare(BASELINE, tmp_path / "no-such-run", "--root", tmp_path)

    assert code == 3
    assert "no Run" in text


def test_a_run_is_found_by_its_id_under_the_root(tmp_path: Path) -> None:
    runs = tmp_path / ".agentdiag" / "targets" / "toy-order-desk" / "runs"
    for run in (BASELINE, MODEL_SWAP):
        shutil.copytree(run, runs / run.name)

    code, _ = compare(BASELINE.name, MODEL_SWAP.name, "--root", tmp_path)

    assert code == 0


def test_compare_reads_the_two_run_directories_and_nothing_else(tmp_path: Path) -> None:
    """No index, no Manifest, no Trace: only each Run's `run.json` and `scorecard.json`."""
    for run in (BASELINE, MODEL_SWAP):
        (tmp_path / run.name).mkdir()
        for name in ("run.json", "scorecard.json"):
            shutil.copyfile(run / name, tmp_path / run.name / name)

    isolated = comparison(tmp_path / BASELINE.name, tmp_path / MODEL_SWAP.name)

    assert isolated == comparison(BASELINE, MODEL_SWAP)


# --- how often decision 37's fallback fired, in the Judge block (ticket 21, decision 39) ---


def with_cites_read(run: Path, tmp_path: Path, count: int) -> Path:
    """A copy of a fixture Run whose Scorecard says its Judge's cites were read `count`
    times as the Span ids they begin with."""
    copy = tmp_path / run.name
    shutil.copytree(run, copy)
    scorecard = json.loads((copy / "scorecard.json").read_text(encoding="utf-8"))
    scorecard["cites_read"] = count
    (copy / "scorecard.json").write_text(json.dumps(scorecard, indent=2), encoding="utf-8")
    return copy


def test_compare_says_how_often_either_judge_had_its_cites_read_as_span_ids(
    tmp_path: Path,
) -> None:
    run = with_cites_read(RESCORE, tmp_path, 2)

    found = comparison(BASELINE, run)
    _, text = compare(BASELINE, run)

    assert found.cites_read == CitesRead(baseline=0, run=2)
    lines = text.splitlines()
    line = "Judge cites read as Span ids: baseline 0, run 2 (decision 37)"
    assert line in lines
    assert lines.index(line) < next(i for i, x in enumerate(lines) if x.startswith("scenarios"))


def test_compare_prints_no_cites_read_line_when_neither_judge_needed_the_fallback() -> None:
    found = comparison(BASELINE, RESCORE)
    _, text = compare(BASELINE, RESCORE)

    assert found.cites_read == CitesRead(baseline=0, run=0)
    assert "cites read" not in text


# --- ticket 06: the Simulated User and the reviewer are configuration (decision 52) ---


def test_compare_diffs_the_simulated_user_and_the_reviewer_but_not_their_prompt_texts() -> None:
    from agentdiag.run.compare import configuration, differences

    prompt = {"version": "simulated_user.v1", "text": "the whole prompt", "fingerprint": "f1"}
    review = {"version": "simulated_user_review.v1", "text": "the review", "fingerprint": "r1"}
    base = {
        "simulated_user": {"model": "claude-sonnet-5", "prompt": prompt, "fingerprint": "a"},
        "judge": {
            "model": "claude-opus-5",
            "reviewer": {"model": "claude-opus-5", "prompt": review},
        },
    }
    other = {
        "simulated_user": {
            "model": "claude-haiku-4-5",
            "prompt": {**prompt, "text": "reworded"},
            "fingerprint": "b",
        },
        "judge": {
            "model": "claude-opus-5",
            "reviewer": {"model": "claude-opus-5-5", "prompt": {**review, "text": "else"}},
        },
    }

    paths = [path for path, _, _ in differences(configuration(base, []), configuration(other, []))]

    assert paths == [
        "judge.reviewer.model",
        "simulated_user.fingerprint",
        "simulated_user.model",
    ]


def test_a_reviewer_change_touches_every_score_of_a_simulated_scenario_and_no_other(
    tmp_path: Path,
) -> None:
    """Amended decision 52: the reviewer rewrites every `fail` of a simulated Trial, so a
    `judge.reviewer.*` difference withholds the direction of each of its Scores, mechanical
    ones included, and of no Score of a Scenario without a `simulate` Turn."""
    from agentdiag.run.compare import _judge_touches

    path = "judge.reviewer.model"
    mechanical = ("expect_tools_order", None)
    assert _judge_touches(path, mechanical, False, set(), simulated=True)
    assert _judge_touches(path, ("goal", None), True, set(), simulated=True)
    assert not _judge_touches(path, ("goal", None), True, set(), simulated=False)
    assert _judge_touches(
        "judge.prompts.stop_when.fingerprint", mechanical, False, set(), simulated=True
    )
    assert not _judge_touches(
        "judge.prompts.stop_when.fingerprint", ("goal", None), True, set(), simulated=False
    )


def test_a_reviewer_model_edited_in_a_run_copy_is_judge_changed_on_the_simulated_scenario_only(
    tmp_path: Path,
) -> None:
    """Amended decision 52, end to end: a Run of the adaptive example beside a literal one,
    and a copy of it whose `judge.reviewer.model` is edited."""
    from tests.simulated import RECORDINGS, example_root, only_run

    root = example_root(tmp_path)
    runner.invoke(
        app,
        [
            "run",
            "--root",
            str(root),
            "--scenario",
            "cancel-without-the-order-number",
            "--scenario",
            "where-is-shipped-order",
            "--replay",
            str(RECORDINGS / "toy-orders.jsonl"),
        ],
    )
    baseline = only_run(root)
    edited = tmp_path / "edited"
    shutil.copytree(baseline, edited)
    record = json.loads((edited / "run.json").read_text(encoding="utf-8"))
    assert {entry["id"]: entry["simulated"] for entry in record["scenarios"]} == {
        "where-is-shipped-order": False,
        "cancel-without-the-order-number": True,
    }
    record["run_id"] = "20260925T000000Z-edit"
    record["judge"]["reviewer"]["model"] = "claude-opus-5-5"
    (edited / "run.json").write_text(json.dumps(record), encoding="utf-8")

    found = comparison(baseline, edited)

    simulated = [d for d in found.deltas if d.scenario == "cancel-without-the-order-number"]
    literal = [d for d in found.deltas if d.scenario == "where-is-shipped-order"]
    assert {d.eval for d in simulated} == {"expect_tools_order", "goal"}
    assert all(d.judge_changed and "judge.reviewer.model" in d.because for d in simulated)
    assert literal and not any(d.judge_changed for d in literal)
