"""The Report file: one `RunView`, the renderer and its styles, in one HTML file (D40).

ADR-0005 §11 asks every Run for one self-contained HTML Report, and phase-7 decision 20
says it is the UI's own renderer with the view embedded, not a second rendering path. So
`render_report` writes no markup of its own beyond the page's head: it inlines
`static/style.css` and `static/renderer.js`, the package data `agentdiag serve` also
serves, and sets `window.AGENTDIAG_VIEW` to the view's JSON. The renderer, finding the view
set, reads nothing else and opens on `#report/<run id>`, the Run screen without the shell.

**No external request.** Everything the page needs is in the file, so it opens from a
mail attachment or an air-gapped disk the same as from the Run directory. **Deterministic.**
The same Run files give the same bytes: no generation time, no random id, and the JSON is
the view model's own dump, so a Report can be diffed and a Run fixture regenerated by the
byte. The JSON is embedded inside a `<script>`, where `</script>` would end it early and
`<!--` followed by `<script` would put the parser in the double-escaped state and blank the
page, so every `<`, `>` and `&` in it is written as its `\\u` escape, which JSON reads back
as the same string: no Trace text can form markup there.

`render_page` is the same document without a view, what `agentdiag serve` sends at `/`.

`write_report` is what `run`, `rescore` and `import` call after `scorecard.json`: a Run
directory is written once (ADR-0005 §2), so it never overwrites an existing `report.html`.
"""

from __future__ import annotations

import json
import sys
from html import escape
from importlib.resources import files
from pathlib import Path

from agentdiag.report.view import RunView, run_view
from agentdiag.run.locate import REPORT_FILE

STATIC = files("agentdiag.report") / "static"


def render_report(view: RunView) -> str:
    """The Report of one Run as a complete HTML document, a pure function of `view`."""
    payload = (
        json.dumps(view.model_dump(mode="json"), ensure_ascii=False, separators=(",", ":"))
        .replace("&", "\\u0026")
        .replace("<", "\\u003c")
        .replace(">", "\\u003e")
    )
    return _document(
        f"agentdiag Report · {view.header.run_id}",
        f"<script>window.AGENTDIAG_VIEW={payload};</script>\n",
    )


def render_page(token: str = "") -> str:
    """The page `agentdiag serve` sends at `/`: the same renderer and styles with no view
    embedded, so it reads the `/api/…` routes and opens on the Dashboard. `token` is the
    server's page token, which the renderer sends with every write and every follow."""
    return _document("agentdiag", f"<script>window.AGENTDIAG_TOKEN={json.dumps(token)};</script>\n")


def _document(title: str, view_script: str) -> str:
    style = (STATIC / "style.css").read_text(encoding="utf-8")
    script = (STATIC / "renderer.js").read_text(encoding="utf-8")
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{escape(title)}</title>\n"
        f"<style>\n{style}</style>\n</head>\n<body>\n"
        f"{view_script}"
        f"<script>\n{script}</script>\n"
        "</body>\n</html>\n"
    )


def write_report(run_dir: Path) -> Path | None:
    """Render a finished Run directory's Report into it as `report.html`, written once.

    Never raises: the Run is complete once its Scorecard is written, so a Report that cannot
    be made, for any reason, is a `warning:` on stderr naming the Run and the exception,
    None is returned, and the Run's exit code and its Index row are its own.
    """
    path = Path(run_dir) / REPORT_FILE
    try:
        html = render_report(run_view(Path(run_dir)))
        with path.open("x", encoding="utf-8", newline="\n") as handle:
            handle.write(html)
    except Exception as exc:  # a Report must never cost a complete Run
        print(
            f"warning: Run {Path(run_dir).name} is complete but wrote no {REPORT_FILE} "
            f"({type(exc).__name__}: {exc})",
            file=sys.stderr,
        )
        return None
    return path


__all__ = ["REPORT_FILE", "render_page", "render_report", "write_report"]
