#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the one thing only a human can do — put credentials on this machine
# (D15, D16). agentdiag never stores a key; it only asks whether one resolves.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# Everything is written relative to the repository root, whichever directory
# the wizard was invoked from.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"

banner "agentdiag credentials"

# ── Stage 1: the Claude Code login (ticket 19) ────────────────────────────
stage "Claude Code login"
say "If you are logged in to Claude Code, the Judge's calls go through it:"
say "no key in a file, nothing to export. With no API key set, it is the default."
note "agentdiag asks the CLI ('claude auth status'); it never reads the CLI's files."
if command -v claude >/dev/null 2>&1; then
  say "What 'claude auth status' says — look for \"loggedIn\": true:"
  printf '\n'
  claude auth status || true
  printf '\n'
  if confirm "Run 'claude auth login' now (skip it if you are already logged in)?"; then
    claude auth login || warn "the login did not finish; re-run this wizard"
  fi
else
  note "No 'claude' on your PATH. agentdiag's Agent SDK bundles its own CLI, which"
  note "reads the same login store, so a login made elsewhere still counts; stage 4"
  note "(verify) is the ground truth. To log in, install Claude Code first:"
  open_url "https://docs.claude.com/en/docs/claude-code/setup"
  SKIPPED+=("claude auth login (no 'claude' on PATH)")
fi
note "This stage writes nothing. The Target still calls the API with a key of its own."

# ── Stage 2: an API key in an untracked .env ──────────────────────────────
stage "Alternative: an API key"
say "Needed when you want the API backend for the Judge, a key for CI, or a"
say "Target that calls the API — the toy example's does, once per Trial."
say "agentdiag never stores your key. This stage puts one in an untracked .env file."
note "An exported key wins over the Claude Code login."
if confirm "Set up an API key now?"; then
  open_url "https://console.anthropic.com/settings/keys"
  step "Sign in, then click 'Create Key' (top right of the API keys page)."
  step "Name it something you'll recognise later, such as 'agentdiag local'."
  step "Click 'Copy' — the key is shown once and never again. Then close the dialog."
  ask_secret ANTHROPIC_API_KEY "Paste the key (input is hidden):"
  if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
    SKIPPED+=("ANTHROPIC_API_KEY (nothing was pasted; re-run this wizard)")
    warn "nothing pasted, so nothing was written"
  else
    # .env holds a secret, so it must never be tracked. Check before writing.
    if grep -qxE '\.env' .gitignore 2>/dev/null; then
      note ".env is already in .gitignore"
    else
      printf '\n# Local credentials; never committed.\n.env\n' >> .gitignore
      say "added .env to .gitignore"
    fi
    write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
    say "Load it into this shell — .env is a file, not an environment:"
    note "  set -a; . ./.env; set +a"
    pause "Copy that line, then press Enter."
  fi
else
  say "Skipped. The Claude Code login, or the 'ant' CLI in stage 3, covers the Judge."
fi

# ── Stage 3: the `ant auth login` alternative ─────────────────────────────
stage "Alternative: ant auth login"
say "The 'ant' CLI keeps a credential profile on disk that agentdiag reads"
say "through the SDK — no key in a file, no variable to export."
note "It is a separate Go binary, latest v1.34.0, and is not installed here."
if confirm "Open the releases page and set it up?"; then
  open_url "https://github.com/anthropics/anthropic-cli/releases"
  step "Download the build for your platform from the latest release."
  step "Unpack it and put 'ant' somewhere on your PATH (e.g. ~/.local/bin/ant)."
  step "Run: ant auth login — it opens a browser and stores a profile."
  step "Then run: ant auth status — it should name the profile you just made."
  pause "Press Enter once 'ant auth status' looks right."
else
  say "Skipped. The Claude Code login or the API key is all the Judge needs."
fi

# ── Stage 4: verify, and optionally spend money ───────────────────────────
stage "Verify"
say "agentdiag resolves credentials the SDK's way, then the Claude Code login, and"
say "reports the source name, never the secret. This asks it what it found."
printf '\n'
if uv run python -c "from agentdiag.model.credentials import resolve; print(resolve())"; then
  printf '\n'
else
  warn "that command failed; run 'uv sync' and try this stage again"
fi
say "A line naming a source means a Run will work. 'None' means nothing resolved:"
note "  re-run this wizard, or load the .env with: set -a; . ./.env; set +a"
printf '\n'
say "The live example runs the toy Target against the real API (it needs the key)"
say "and the Judge through whichever source resolved above."
warn "It costs money — a few cents for one Scenario and one judged Eval."
if confirm "Run the live example now?"; then
  uv run agentdiag run --root examples/toy --scenario cancel-processing-order || \
    warn "the Run exited non-zero; its Scorecard above says why"
  pause "Press Enter to finish."
else
  say "Skipped. Run it without credentials any time:"
  note "  uv run agentdiag run --root examples/toy --scenario cancel-processing-order \\"
  note "    --replay tests/fixtures/recordings/toy-cancel.jsonl"
fi

finish
